### ISSUE TITLE
小白请教一下，这个工具怎么打开呀

### ISSUE THREAD

**Issue by xuelu55** [TonyChenn/HexoBlogWriteTool#1]

**Comment by TonyChenn** [comment]
只上传了源码，可以自行编译，也可以下载：
[HexoWriteTool.zip](https://github.com/TonyChenn/HexoBlogWriteTool/files/6550752/HexoWriteTool.zip)

创建新文章后需要改下日期格式，xxxx/xxxx/xxxx 改成 xxxx-xx-xx 18:06:15

**Comment by TonyChenn** [comment]
> _No description provided._

刚不小心关掉了

下载地址：
[HexoWriteTool.zip](https://github.com/TonyChenn/HexoBlogWriteTool/files/6550771/HexoWriteTool.zip)

**Comment by TonyChenn** [comment]
创建文章后需要改下时间的格式：xxxx/xx/xx   改成   2021-05-27 10:54:00

**Comment by xuelu55** [comment]
谢谢啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月27日(周四) 上午10:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TonyChenn/HexoBlogWriteTool] 小白请教一下，这个工具怎么打开呀 (#1)




 
创建文章后需要改下时间的格式：xxxx/xx/xx   改成   2021-05-27 10:54:00
